# Generated by Django 6.0.7 on 2026-07-09 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('serial', models.CharField(max_length=100)),
                ('command', models.CharField(max_length=100)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pond',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('serial', models.CharField(max_length=100)),
                ('hopper_percent', models.FloatField(default=100.0)),
            ],
        ),
        migrations.CreateModel(
            name='FeedSchedule',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('time', models.CharField(blank=True, max_length=32, null=True)),
                ('amount_grams', models.FloatField(blank=True, null=True)),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='api.pond')),
            ],
        ),
        migrations.CreateModel(
            name='FeedLog',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('serial', models.CharField(max_length=100)),
                ('amount_grams', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('pond', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.pond')),
            ],
        ),
    ]
