# Generated by Django 6.0.7 on 2026-07-13 09:33

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_device'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('farm_name', models.CharField(blank=True, max_length=120)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DeviceCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_serial', models.CharField(db_index=True, max_length=50)),
                ('command_type', models.CharField(choices=[('feed_now', 'Feed Now'), ('update_schedule', 'Update Schedule'), ('firmware_update', 'Firmware Update'), ('sync', 'Sync EEPROM')], max_length=30)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'device_commands',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceInfo',
            fields=[
                ('serial', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pond_name', models.CharField(max_length=100)),
                ('firmware_version', models.CharField(max_length=20)),
                ('latest_firmware', models.CharField(max_length=20)),
                ('wifi_rssi', models.IntegerField()),
                ('ping_ms', models.IntegerField()),
                ('uptime_seconds', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('hardware_status', models.JSONField(default=dict)),
                ('firmware_update_available', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'device_info',
            },
        ),
        migrations.CreateModel(
            name='SyncStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending_uploads', models.IntegerField(default=0)),
                ('failed_retries', models.IntegerField(default=0)),
                ('recovered_events', models.IntegerField(default=0)),
                ('last_sync_time', models.DateTimeField(auto_now=True)),
                ('eeprom_healthy', models.BooleanField(default=True)),
                ('eeprom_used_bytes', models.IntegerField(default=0)),
                ('eeprom_total_bytes', models.IntegerField(default=4096)),
            ],
            options={
                'db_table': 'sync_status',
            },
        ),
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_serial', models.CharField(db_index=True, max_length=50)),
                ('food_level_pct', models.FloatField()),
                ('water_temp', models.FloatField(blank=True, null=True)),
                ('wifi_rssi', models.IntegerField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'telemetry',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.DeleteModel(
            name='Command',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.AlterModelOptions(
            name='feedlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='feedschedule',
            options={'ordering': ['hour', 'minute']},
        ),
        migrations.AlterModelOptions(
            name='pond',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='feedlog',
            name='amount_grams',
        ),
        migrations.RemoveField(
            model_name='feedlog',
            name='pond',
        ),
        migrations.RemoveField(
            model_name='feedlog',
            name='serial',
        ),
        migrations.RemoveField(
            model_name='feedschedule',
            name='amount_grams',
        ),
        migrations.RemoveField(
            model_name='feedschedule',
            name='time',
        ),
        migrations.RemoveField(
            model_name='pond',
            name='hopper_percent',
        ),
        migrations.RemoveField(
            model_name='pond',
            name='serial',
        ),
        migrations.AddField(
            model_name='feedlog',
            name='pond_name',
            field=models.CharField(db_index=True, default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='feedlog',
            name='portion_grams',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='feedlog',
            name='synced',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='feedlog',
            name='trigger_type',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('manual', 'Manual')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='feedschedule',
            name='duration_seconds',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='feedschedule',
            name='hour',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)]),
        ),
        migrations.AddField(
            model_name='feedschedule',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='feedschedule',
            name='minute',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)]),
        ),
        migrations.AddField(
            model_name='feedschedule',
            name='portion_grams',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='feedschedule',
            name='weekdays',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='pond',
            name='feeder_serial',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='pond',
            name='food_percent',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='pond',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pond',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pond',
            name='next_feed_time',
            field=models.CharField(default='Offline', max_length=20),
        ),
        migrations.AddField(
            model_name='pond',
            name='water_temp',
            field=models.FloatField(default=25.0),
        ),
        migrations.AlterField(
            model_name='feedlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='feedschedule',
            name='pond',
            field=models.ForeignKey(db_column='pond_name', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='api.pond', to_field='name'),
        ),
        migrations.AlterField(
            model_name='pond',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pond',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterModelTable(
            name='feedlog',
            table='feed_logs',
        ),
        migrations.AlterModelTable(
            name='feedschedule',
            table='feed_schedules',
        ),
        migrations.AlterModelTable(
            name='pond',
            table='ponds',
        ),
        migrations.AddField(
            model_name='pond',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ponds', to=settings.AUTH_USER_MODEL),
        ),
    ]
